[package]
name = "lnd-client"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>", "SÃ¶nke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.3", features = ["blocking"] }

[dev-dependencies]
cradle = { git = "https://github.com/soenkehahn/cradle", rev = "508c646" }
httpmock = "0.5.8"
pretty_assertions = "0.7.2"
tempfile = "3.2.0"
