[package]
name = "foo"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>", "SÃ¶nke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[dependencies]
maud = "0.22.2"

[dependencies.hyper]
version = "0.14.7"
features = ["server"]

[dependencies.tokio]
version = "1.5.0"
features = ["rt", "rt-multi-thread", "macros"]

[dev-dependencies]
reqwest = "0.11.3"
