[package]
name = "foo"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>", "SÃ¶nke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.14"
maud = "0.22.2"
structopt = "0.3.21"
snafu = "0.6.10"

[dependencies.tower]
version = "0.4.6"
features = ["make"]

[dependencies.hyper]
version = "0.14.7"
features = ["server"]

[dependencies.tokio]
version = "1.5.0"
features = ["rt", "rt-multi-thread", "macros", "fs"]

[dev-dependencies]
guard = "0.5.1"
pretty_assertions = "0.7.2"
scraper = "0.12.0"
tempfile = "3.2.0"
executable-path = "1.0.0"

[dev-dependencies.reqwest]
version = "0.11.3"
features = ["blocking"]

[[test]]
name = "smoke"
path = "tests/smoke.rs"
test = false
