[package]
name = "foo"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>", "SÃ¶nke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

[dependencies]
maud = "0.22.2"
tempfile = "3.2.0"
futures = "0.3.14"
anyhow = "1.0.40"

[dependencies.tower]
version = "0.4.6"
features = ["make"]

[dependencies.hyper]
version = "0.14.7"
features = ["server"]

[dependencies.tokio]
version = "1.5.0"
features = ["rt", "rt-multi-thread", "macros", "fs"]

[dev-dependencies]
reqwest = "0.11.3"
