[package]
name = "agora"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>", "SÃ¶nke Hahn <soenkehahn@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
bytes = "1.0.1"
futures = "0.3.14"
maud = "0.22.2"
mime_guess = "2.0.3"
percent-encoding = "2.1.0"
pin-project = "1.0.7"
rust-embed = "5.9.0"
snafu = "0.6.10"
structopt = "0.3.21"

[dependencies.tower]
version = "0.4.6"
features = ["make"]

[dependencies.hyper]
version = "0.14.7"
features = ["server", "stream", "tcp", "http1", "http2"]

[dependencies.tokio]
version = "1.5.0"
features = ["rt", "rt-multi-thread", "macros", "fs"]

[dev-dependencies]
executable-path = "1.0.0"
guard = "0.5.1"
libc = "0.2.94"
nix = "0.20.0"
pretty_assertions = "0.7.2"
scraper = "0.12.0"
tempfile = "3.2.0"

[target.'cfg(not(windows))'.dev-dependencies.openssl]
version = "*"
features = ["vendored"]

[dev-dependencies.reqwest]
version = "0.11.3"
features = ["blocking", "stream"]

[[test]]
name = "smoke"
path = "tests/smoke.rs"
test = false
